ALL_FEATURES = ["no_mean",
                "stim_mean",
                "no_std",
                "stim_std",
                "no_var",
                "stim_var",
                "no_skew",
                "stim_skew",
                "no_kurt",
                "stim_kurt",
                "no_iqr",
                "stim_iqr",
                "no_hjorth_mob",
                "stim_hjorth_mob",
                "no_hjorth_comp",
                "stim_hjorth_comp",
                "no_wavelet_entropy",
                "stim_wavelet_entropy",
                "no_power_spectral_density",
                "stim_power_spectral_density"]

NO_FEATURES = ["no_mean",
                "no_std",
                "no_var",
                "no_skew",
                "no_kurt",
                "no_iqr",
                "no_hjorth_mob",
                "no_hjorth_comp",
                "no_wavelet_entropy",
                "no_power_spectral_density"]

STIM_FEATURES = ["stim_mean",
                "stim_std",
                "stim_var",
                "stim_skew",
                "stim_kurt",
                "stim_iqr",
                "stim_hjorth_mob",
                "stim_hjorth_comp",
                "stim_wavelet_entropy",
                "stim_power_spectral_density"]

SENSOR_NAMES = ["pn1", "pn3", "mu_ch1", "mu_ch2"]